Implement Ably Rule Resource with Zapier Target
ably/terraform-provider-ably pull request #107
Opened 2022-09-14 21:07 UTC by graham-russell

This PR includes the following items
- tfplugindocs generated documentation
- Ably Zapier integration rule resource with inbuilt source and target.
- Updates to provider and models to represent Ably Rule for Zapier target
- Playground tf templates updated
- Resource example updated for Zapier integration rule
- Acceptance testing configured

2022-09-15 11:59 UTC, graham-russell commented
Note: Moving this to draft as I'll be rebasing off of Morgan's work on rules.

2022-09-16 10:46 UTC, Morganamilo requested changes

2022-09-16 10:46 UTC, Morganamilo commented on internal/provider/resource_ably_rule_zapier.go
> +			"headers": {
This should probably be pulled to a headers function.

2022-09-16 10:54 UTC, kavalerov requested changes
Can we please also add high level documentation line to the rule resource, similar to https://github.com/ably/terraform-provider-ably/blob/c5a80850748c871cfd3a50952903eebd7eacc1be/internal/provider/resource_ably_key.go#L83 ? 

The content for the line can be simple "The `ably-rule-zapier` allows you to create and manage Able integration rule for Zapier. Read more at https://ably.com/docs/general/webhooks/zapier"

2022-09-16 12:21 UTC, Morganamilo approved these changes

2022-09-16 12:50 UTC, graham-russell commented
> Can we please also add high level documentation line to the rule resource, similar to
> 
> https://github.com/ably/terraform-provider-ably/blob/c5a80850748c871cfd3a50952903eebd7eacc1be/internal/provider/resource_ably_key.go#L83
> 
> ?
> The content for the line can be simple "The `ably-rule-zapier` allows you to create and manage Able integration rule for Zapier. Read more at https://ably.com/docs/general/webhooks/zapier"

This has been done now for all existing rule resources. (Kinesis/SQS/Lambda/Zapier)

2022-09-16 12:51 UTC, kavalerov commented
Great, thanks!

2022-09-16 12:52 UTC, kavalerov approved these changes
LGTM, thanks

2022-09-16 12:54 UTC, merged