Document publishing process
ably/terraform-provider-ably pull request #84
Opened 2022-08-31 08:49 UTC by kavalerov

Closes #81

2022-08-31 09:28 UTC, QuintinWillison requested changes
Thanks. We usually conform to including this information in `CONTRIBUTING.md`, unless there's a strong reason why - in a Terraform context - one would expect it to be under `PUBLISHING.md`?

See [Client Library SDK Repository - CONTRIBUTING Template](https://github.com/ably/ably-common/blob/main/templates/sdk-contributing.md).

2022-08-31 09:29 UTC, QuintinWillison commented
Oh, just seen a slight conflict with https://github.com/ably/terraform-provider-ably/pull/85 ... relating to my previous comment on this PR.

2022-09-01 08:44 UTC, kavalerov commented
Rebased on top of the #85 , and moved the release process to CONTRIBUTING.md

2022-09-01 09:35 UTC, QuintinWillison approved these changes

2022-09-01 11:21 UTC, merged