Fix the documentation index issues
ably/terraform-provider-ably pull request #96
Opened 2022-09-02 15:01 UTC by kavalerov

2022-09-02 15:04 UTC, kavalerov commented
Unfortunately some small documentation typos found their way into the first release, so fixing them to follow up with a docs fix publish.

2022-09-05 09:01 UTC, graham-russell approved these changes

2022-09-05 09:23 UTC, QuintinWillison requested changes

2022-09-05 09:23 UTC, QuintinWillison commented on templates/index.md.tmpl
> +The support for [Integration rules](https://ably.com/docs/general/integrations) will be added in the future versions.
```suggestion
Support for [Integration rules](https://ably.com/docs/general/integrations) will be added in a future versions.
```

2022-09-05 09:24 UTC, QuintinWillison approved these changes

2022-09-05 09:26 UTC, merged